version: "3"
services:
  nginx:
    image: nginx:1.25
    ports:
      - 80:80
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend

  database:
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - ./etc/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  backend:
    image: golang:1.20
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - database

  frontend:
    image: node:18
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  dbdata:
