name: build-check

on:
    pull_request:
      types: [opened]

jobs:
    frontend-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                    node-version: '18.x'
            - name: Install Frontend Dependencies
              working-directory: ./frontend
              run: npm ci
            - name: Frontend Build Check
              working-directory: ./frontend
              run: npm run build

    backend-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Golang
              uses: actions/setup-go@v4
              with:
                    go-version: '1.20'
            - name: Install Backend Dependencies
              working-directory: ./backend
              run: go mod download
            - name: Backend Build Check
              working-directory: ./backend
              run: go build -o main .


        
