name: build-check

on:
    push:
        branches:
            - feat/*
            - fix/*
            - hotfix/*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                    node-version: '18.x'
            - name: Setup Golang
              uses: actions/setup-go@v2
              with:
                    go-version: '1.20'
            - name: Install Frontend Dependencies
              working-directory: ./frontend
              run: npm ci
            - name: Frontend Build Check
              working-directory: ./frontend
              run: npm run build
            - name: Install Backend Dependencies
              working-directory: ./backend
              run: go mod download
            - name: Backend Build Check
              working-directory: ./backend
              run: go build -o main .


        
